version: '3'
services:
    core_services:
        build:
            context: ./docker_data/core/
        container_name: core_$DB_DATABASE
        ports:
            - 8080:80
        volumes:
            - "./:/var/www/"
            - "./public/:/var/www/html/"
            - "./docker_data/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        networks:
            - backend
    mysql:
        container_name: db_mysql_$DB_DATABASE
        image: mysql:5.7
        ports:
            - 33062:3306
        environment:
            - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
        volumes:
            - "./docker_data/mysql/db/data:/var/lib/mysql"
            - "./docker_data/mysql/db/initdb.d:/docker-entrypoint-initdb.d"
        networks:
            - backend
    pma:
        container_name: pma_$DB_DATABASE
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        volumes:
            - "./docker_data/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        environment:
            - "PMA_HOST=db_mysql_${DB_DATABASE}"
            - "MYSQL_DATABASE=${DB_DATABASE}"
            - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
        networks:
            - backend

networks:
    backend:
        driver: bridge
