<?php

namespace MediactiveDigital\MedKit\Traits;

use Carbon\Carbon;

use MediactiveDigital\MedKit\Helpers\Helper;

use Illuminate\Support\ViewErrorBag;

use DB;
use Str;
use Session;
use App;

trait Form {

    /** 
     * @var int 
     */
    private static $defaultChoiceLimit = 100;

    /** 
     * Format datetime.
     *
     * @param mixed $date
     * @return \Closure
     */
    private function formatDateTime() {

        return function($date) {

            return $date ? Carbon::parse($date)->format('Y-m-d\TH:i:s') : $date;
        };
    }

    /** 
     * Format JSON.
     *
     * @param string $key
     * @param mixed $array
     * @return \Closure
     */
    private function formatJson(string $key = 'value') {

        return function($array) use ($key) {

            $value = is_array($array) && $array ? (isset($array[$key]) ? $array[$key] : reset($array)) : $array;
            $value = is_string($value) ? $value : '';

            return $value;
        };
    }

    /** 
     * Format null.
     *
     * @param mixed $value
     * @return \Closure
     */
    private function formatNull() {

        return function($value) {

            return null;
        };
    }

    /** 
     * Set attribute.
     *
     * @param mixed $createValue
     * @param mixed $updateValue
     * @return mixed
     */
    private function setAttribute($createValue, $updateValue = null) {

        return $this->model ? $updateValue : $createValue;
    }

    /** 
     * Get select choices.
     *
     * @param string $table
     * @param string $label
     * @param int $limit
     * @return array $choices 
     */
    private function getChoices(string $table, string $label = '', int $limit = 0): array {

        $choices = [];

        if (($table = Helper::getTableName($table)) && ($primary = Helper::getTablePrimaryName($table))) {

            $label = Helper::getTableLabelName($table, $label);
            $select = $label;
            $limit = $limit ?: self::$defaultChoiceLimit;

            if (!$label) {

                $label = 'label';
                $select = DB::raw('CONCAT(\'' . addcslashes(Str::ucfirst(str_replace('_', ' ', Str::singular(Str::lower($table)))), '\'') . ' ' . '\', `' . $primary . '`)  AS `' . $label . '`');
            }

            $class = Helper::getClassNameFromTableName($table);
            $query = $class ? $class::query() : DB::table($table);
            $relations = $query->select([$primary, $select])->orderBy($label);

            if ($limit > 0) {

            	$relations->limit($limit);
            }

            if ($this->model && ($selfTable = $this->model->getTable()) && $selfTable == $table && ($primaryKey = Helper::getTablePrimaryName($selfTable))) {

                $relations->where($primaryKey, '!=', $this->model->{$primaryKey});
            }

            $relations = $relations->get();
            $choices = $relations ? $relations->pluck($label, $primary)->toArray() : $choices;
        }

        return $choices;
    }

    /**
     * Get Bootstrap 4 badges select choices.
     *
     * @return array
     */
    private function getBadgesChoices() {

        return [ 
            'primary' => 'Primary',  
            'secondary' => 'Secondary',  
            'success' => 'Success',  
            'danger' => 'Danger',  
            'warning' => 'Warning',  
            'info' => 'Info',  
            'light' => 'Light',  
            'dark' => 'Dark'
        ];
    }

    /**
     * Create translatable fields and add them to the form.
     *
     * @param string $name
     * @param string $type
     * @param array $options
     * @param bool $modify
     * @return void
     */
    private function addTranslatable(string $name, string $type = 'text', array $options = [], bool $modify = false) {

        $options['subtype'] = $type;

        $this->add($name, 'translatable', $options, $modify);
    }

    /**
     * Get the form error bag.
     *
     * @return string
     */
    public function getErrorBag(): string {

        return $this->getData('error_bag') ?: $this->errorBag;
    }
    
    /**
     * Get the current session errors bound to the form.
     *
     * @return array
     */
    public function getSessionErrors(): array {

        return Session::get('errors', App::make(ViewErrorBag::class))->getBag($this->getErrorBag())->getMessages();
    }
   
    /**
     * Get Material Icons select choices.
     *
	 * @param array $byGroups enum : action, alert, av, communication, content, device, editor, file, hardware, image, maps, navigation, notification, places, social, toggle
	 * @param array $byIcons
	 * 
	 * @return array
	 */
    private function getMaterialIconsChoices( $byGroups = [], $byIcons = [] ) {

		$allCat = [
			'action',
			'alert',
			'av',
			'communication',
			'content',
			'device',
			'editor',
			'file',
			'hardware',
			'image',
			'maps',
			'navigation',
			'notification',
			'places',
			'social',
			'toggle'
		];
		
		/**
		 * Tout les icons.
		 * Formule magic d'extraction :
		 $('.icon-item-container').each(function(){console.log("'" + $(this).attr('title') +"'" + "=>"+ "'" + $(this).attr('title') +"'" + ', ')});
		 */
		$action = [
			'compare_arrows'			 => 'compare_arrows',
			'3d_rotation'				 => '3d_rotation',
			'accessibility'				 => 'accessibility',
			'accessibility_new'			 => 'accessibility_new',
			'accessible'				 => 'accessible',
			'accessible_forward'		 => 'accessible_forward',
			'account_balance'			 => 'account_balance',
			'account_balance_wallet'	 => 'account_balance_wallet',
			'account_box'				 => 'account_box',
			'account_circle'			 => 'account_circle',
			'add_shopping_cart'			 => 'add_shopping_cart',
			'alarm'						 => 'alarm',
			'alarm_add'					 => 'alarm_add',
			'alarm_off'					 => 'alarm_off',
			'alarm_on'					 => 'alarm_on',
			'all_inbox'					 => 'all_inbox',
			'all_out'					 => 'all_out',
			'android'					 => 'android',
			'announcement'				 => 'announcement',
			'arrow_right_alt'			 => 'arrow_right_alt',
			'aspect_ratio'				 => 'aspect_ratio',
			'assessment'				 => 'assessment',
			'assignment'				 => 'assignment',
			'assignment_ind'			 => 'assignment_ind',
			'assignment_late'			 => 'assignment_late',
			'assignment_return'			 => 'assignment_return',
			'assignment_returned'		 => 'assignment_returned',
			'assignment_turned_in'		 => 'assignment_turned_in',
			'autorenew'					 => 'autorenew',
			'backup'					 => 'backup',
			'book'						 => 'book',
			'bookmark'					 => 'bookmark',
			'bookmark_border'			 => 'bookmark_border',
			'bookmarks'					 => 'bookmarks',
			'bug_report'				 => 'bug_report',
			'build'						 => 'build',
			'cached'					 => 'cached',
			'calendar_today'			 => 'calendar_today',
			'calendar_view_day'			 => 'calendar_view_day',
			'camera_enhance'			 => 'camera_enhance',
			'cancel_schedule_send'		 => 'cancel_schedule_send',
			'card_giftcard'				 => 'card_giftcard',
			'card_membership'			 => 'card_membership',
			'card_travel'				 => 'card_travel',
			'change_history'			 => 'change_history',
			'check_circle'				 => 'check_circle',
			'check_circle_outline'		 => 'check_circle_outline',
			'chrome_reader_mode'		 => 'chrome_reader_mode',
			'class'						 => 'class',
			'code'						 => 'code',
			'commute'					 => 'commute',
			'contact_support'			 => 'contact_support',
			'contactless'				 => 'contactless',
			'copyright'					 => 'copyright',
			'credit_card'				 => 'credit_card',
			'dashboard'					 => 'dashboard',
			'date_range'				 => 'date_range',
			'delete'					 => 'delete',
			'delete_forever'			 => 'delete_forever',
			'delete_outline'			 => 'delete_outline',
			'description'				 => 'description',
			'dns'						 => 'dns',
			'done'						 => 'done',
			'done_all'					 => 'done_all',
			'done_outline'				 => 'done_outline',
			'donut_large'				 => 'donut_large',
			'donut_small'				 => 'donut_small',
			'drag_indicator'			 => 'drag_indicator',
			'eco'						 => 'eco',
			'eject'						 => 'eject',
			'euro_symbol'				 => 'euro_symbol',
			'event'						 => 'event',
			'event_seat'				 => 'event_seat',
			'exit_to_app'				 => 'exit_to_app',
			'explore'					 => 'explore',
			'explore_off'				 => 'explore_off',
			'extension'					 => 'extension',
			'face'						 => 'face',
			'favorite'					 => 'favorite',
			'favorite_border'			 => 'favorite_border',
			'feedback'					 => 'feedback',
			'find_in_page'				 => 'find_in_page',
			'find_replace'				 => 'find_replace',
			'fingerprint'				 => 'fingerprint',
			'flight_land'				 => 'flight_land',
			'flight_takeoff'			 => 'flight_takeoff',
			'flip_to_back'				 => 'flip_to_back',
			'flip_to_front'				 => 'flip_to_front',
			'g_translate'				 => 'g_translate',
			'gavel'						 => 'gavel',
			'get_app'					 => 'get_app',
			'gif'						 => 'gif',
			'grade'						 => 'grade',
			'group_work'				 => 'group_work',
			'help'						 => 'help',
			'help_outline'				 => 'help_outline',
			'highlight_off'				 => 'highlight_off',
			'history'					 => 'history',
			'home'						 => 'home',
			'horizontal_split'			 => 'horizontal_split',
			'hourglass_empty'			 => 'hourglass_empty',
			'hourglass_full'			 => 'hourglass_full',
			'http'						 => 'http',
			'https'						 => 'https',
			'important_devices'			 => 'important_devices',
			'info'						 => 'info',
			'input'						 => 'input',
			'invert_colors'				 => 'invert_colors',
			'label'						 => 'label',
			'label_important'			 => 'label_important',
			'label_off'					 => 'label_off',
			'language'					 => 'language',
			'launch'					 => 'launch',
			'line_style'				 => 'line_style',
			'line_weight'				 => 'line_weight',
			'list'						 => 'list',
			'lock'						 => 'lock',
			'lock_open'					 => 'lock_open',
			'loyalty'					 => 'loyalty',
			'markunread_mailbox'		 => 'markunread_mailbox',
			'maximize'					 => 'maximize',
			'minimize'					 => 'minimize',
			'motorcycle'				 => 'motorcycle',
			'note_add'					 => 'note_add',
			'offline_bolt'				 => 'offline_bolt',
			'offline_pin'				 => 'offline_pin',
			'opacity'					 => 'opacity',
			'open_in_browser'			 => 'open_in_browser',
			'open_in_new'				 => 'open_in_new',
			'open_with'					 => 'open_with',
			'pageview'					 => 'pageview',
			'pan_tool'					 => 'pan_tool',
			'payment'					 => 'payment',
			'perm_camera_mic'			 => 'perm_camera_mic',
			'perm_contact_calendar'		 => 'perm_contact_calendar',
			'perm_data_setting'			 => 'perm_data_setting',
			'perm_device_information'	 => 'perm_device_information',
			'perm_identity'				 => 'perm_identity',
			'perm_media'				 => 'perm_media',
			'perm_phone_msg'			 => 'perm_phone_msg',
			'perm_scan_wifi'			 => 'perm_scan_wifi',
			'pets'						 => 'pets',
			'picture_in_picture'		 => 'picture_in_picture',
			'picture_in_picture_alt'	 => 'picture_in_picture_alt',
			'play_for_work'				 => 'play_for_work',
			'polymer'					 => 'polymer',
			'power_settings_new'		 => 'power_settings_new',
			'pregnant_woman'			 => 'pregnant_woman',
			'print'						 => 'print',
			'query_builder'				 => 'query_builder',
			'question_answer'			 => 'question_answer',
			'receipt'					 => 'receipt',
			'record_voice_over'			 => 'record_voice_over',
			'redeem'					 => 'redeem',
			'remove_shopping_cart'		 => 'remove_shopping_cart',
			'reorder'					 => 'reorder',
			'report_problem'			 => 'report_problem',
			'restore'					 => 'restore',
			'restore_from_trash'		 => 'restore_from_trash',
			'restore_page'				 => 'restore_page',
			'room'						 => 'room',
			'rounded_corner'			 => 'rounded_corner',
			'rowing'					 => 'rowing',
			'schedule'					 => 'schedule',
			'search'					 => 'search',
			'settings'					 => 'settings',
			'settings_applications'		 => 'settings_applications',
			'settings_backup_restore'	 => 'settings_backup_restore',
			'settings_bluetooth'		 => 'settings_bluetooth',
			'settings_brightness'		 => 'settings_brightness',
			'settings_cell'				 => 'settings_cell',
			'settings_ethernet'			 => 'settings_ethernet',
			'settings_input_antenna'	 => 'settings_input_antenna',
			'settings_input_component'	 => 'settings_input_component',
			'settings_input_composite'	 => 'settings_input_composite',
			'settings_input_hdmi'		 => 'settings_input_hdmi',
			'settings_input_svideo'		 => 'settings_input_svideo',
			'settings_overscan'			 => 'settings_overscan',
			'settings_phone'			 => 'settings_phone',
			'settings_power'			 => 'settings_power',
			'settings_remote'			 => 'settings_remote',
			'settings_voice'			 => 'settings_voice',
			'shop'						 => 'shop',
			'shop_two'					 => 'shop_two',
			'shopping_basket'			 => 'shopping_basket',
			'shopping_cart'				 => 'shopping_cart',
			'speaker_notes'				 => 'speaker_notes',
			'speaker_notes_off'			 => 'speaker_notes_off',
			'spellcheck'				 => 'spellcheck',
			'stars'						 => 'stars',
			'store'						 => 'store',
			'subject'					 => 'subject',
			'supervised_user_circle'	 => 'supervised_user_circle',
			'supervisor_account'		 => 'supervisor_account',
			'swap_horiz'				 => 'swap_horiz',
			'swap_horizontal_circle'	 => 'swap_horizontal_circle',
			'swap_vert'					 => 'swap_vert',
			'swap_vertical_circle'		 => 'swap_vertical_circle',
			'sync_alt'					 => 'sync_alt',
			'system_update_alt'			 => 'system_update_alt',
			'tab'						 => 'tab',
			'tab_unselected'			 => 'tab_unselected',
			'text_rotate_up'			 => 'text_rotate_up',
			'text_rotate_vertical'		 => 'text_rotate_vertical',
			'text_rotation_angledown'	 => 'text_rotation_angledown',
			'text_rotation_angleup'		 => 'text_rotation_angleup',
			'text_rotation_down'		 => 'text_rotation_down',
			'text_rotation_none'		 => 'text_rotation_none',
			'theaters'					 => 'theaters',
			'thumb_down'				 => 'thumb_down',
			'thumb_up'					 => 'thumb_up',
			'thumbs_up_down'			 => 'thumbs_up_down',
			'timeline'					 => 'timeline',
			'toc'						 => 'toc',
			'today'						 => 'today',
			'toll'						 => 'toll',
			'touch_app'					 => 'touch_app',
			'track_changes'				 => 'track_changes',
			'translate'					 => 'translate',
			'trending_down'				 => 'trending_down',
			'trending_flat'				 => 'trending_flat',
			'trending_up'				 => 'trending_up',
			'turned_in'					 => 'turned_in',
			'turned_in_not'				 => 'turned_in_not',
			'update'					 => 'update',
			'verified_user'				 => 'verified_user',
			'vertical_split'			 => 'vertical_split',
			'view_agenda'				 => 'view_agenda',
			'view_array'				 => 'view_array',
			'view_carousel'				 => 'view_carousel',
			'view_column'				 => 'view_column',
			'view_day'					 => 'view_day',
			'view_headline'				 => 'view_headline',
			'view_list'					 => 'view_list',
			'view_module'				 => 'view_module',
			'view_quilt'				 => 'view_quilt',
			'view_stream'				 => 'view_stream',
			'view_week'					 => 'view_week',
			'visibility'				 => 'visibility',
			'visibility_off'			 => 'visibility_off',
			'voice_over_off'			 => 'voice_over_off',
			'watch_later'				 => 'watch_later',
			'work'						 => 'work',
			'work_off'					 => 'work_off',
			'work_outline'				 => 'work_outline',
			'youtube_searched_for'		 => 'youtube_searched_for',
			'zoom_in'					 => 'zoom_in',
			'zoom_out'					 => 'zoom_out',
		];
		$alert = [
			'add_alert'				 => 'add_alert',
			'error'					 => 'error',
			'error_outline'			 => 'error_outline',
			'notification_important' => 'notification_important',
			'warning'				 => 'warning',
		];
		$av = [
			'4k'					 => '4k',
			'add_to_queue'			 => 'add_to_queue',
			'airplay'				 => 'airplay',
			'album'					 => 'album',
			'art_track'				 => 'art_track',
			'av_timer'				 => 'av_timer',
			'branding_watermark'	 => 'branding_watermark',
			'call_to_action'		 => 'call_to_action',
			'closed_caption'		 => 'closed_caption',
			'control_camera'		 => 'control_camera',
			'equalizer'				 => 'equalizer',
			'explicit'				 => 'explicit',
			'fast_forward'			 => 'fast_forward',
			'fast_rewind'			 => 'fast_rewind',
			'featured_play_list'	 => 'featured_play_list',
			'featured_video'		 => 'featured_video',
			'fiber_dvr'				 => 'fiber_dvr',
			'fiber_manual_record'	 => 'fiber_manual_record',
			'fiber_new'				 => 'fiber_new',
			'fiber_pin'				 => 'fiber_pin',
			'fiber_smart_record'	 => 'fiber_smart_record',
			'forward_10'			 => 'forward_10',
			'forward_30'			 => 'forward_30',
			'forward_5'				 => 'forward_5',
			'games'					 => 'games',
			'hd'					 => 'hd',
			'hearing'				 => 'hearing',
			'high_quality'			 => 'high_quality',
			'library_add'			 => 'library_add',
			'library_add_check'		 => 'library_add_check',
			'library_books'			 => 'library_books',
			'library_music'			 => 'library_music',
			'loop'					 => 'loop',
			'mic'					 => 'mic',
			'mic_none'				 => 'mic_none',
			'mic_off'				 => 'mic_off',
			'missed_video_call'		 => 'missed_video_call',
			'movie'					 => 'movie',
			'music_video'			 => 'music_video',
			'new_releases'			 => 'new_releases',
			'not_interested'		 => 'not_interested',
			'note'					 => 'note',
			'pause'					 => 'pause',
			'pause_circle_filled'	 => 'pause_circle_filled',
			'pause_circle_outline'	 => 'pause_circle_outline',
			'play_arrow'			 => 'play_arrow',
			'play_circle_filled'	 => 'play_circle_filled',
			'play_circle_outline'	 => 'play_circle_outline',
			'playlist_add'			 => 'playlist_add',
			'playlist_add_check'	 => 'playlist_add_check',
			'playlist_play'			 => 'playlist_play',
			'queue'					 => 'queue',
			'queue_music'			 => 'queue_music',
			'queue_play_next'		 => 'queue_play_next',
			'radio'					 => 'radio',
			'recent_actors'			 => 'recent_actors',
			'remove_from_queue'		 => 'remove_from_queue',
			'repeat'				 => 'repeat',
			'repeat_one'			 => 'repeat_one',
			'replay'				 => 'replay',
			'replay_10'				 => 'replay_10',
			'replay_30'				 => 'replay_30',
			'replay_5'				 => 'replay_5',
			'shuffle'				 => 'shuffle',
			'skip_next'				 => 'skip_next',
			'skip_previous'			 => 'skip_previous',
			'slow_motion_video'		 => 'slow_motion_video',
			'snooze'				 => 'snooze',
			'sort_by_alpha'			 => 'sort_by_alpha',
			'speed'					 => 'speed',
			'stop'					 => 'stop',
			'subscriptions'			 => 'subscriptions',
			'subtitles'				 => 'subtitles',
			'surround_sound'		 => 'surround_sound',
			'video_call'			 => 'video_call',
			'video_label'			 => 'video_label',
			'video_library'			 => 'video_library',
			'videocam'				 => 'videocam',
			'videocam_off'			 => 'videocam_off',
			'volume_down'			 => 'volume_down',
			'volume_mute'			 => 'volume_mute',
			'volume_off'			 => 'volume_off',
			'volume_up'				 => 'volume_up',
			'web'					 => 'web',
			'web_asset'				 => 'web_asset',
		];
		$communication = [
			'call_made'					 => 'call_made',
			'add_ic_call'				 => 'add_ic_call',
			'alternate_email'			 => 'alternate_email',
			'business'					 => 'business',
			'call'						 => 'call',
			'call_end'					 => 'call_end',
			'call_merge'				 => 'call_merge',
			'call_missed'				 => 'call_missed',
			'call_missed_outgoing'		 => 'call_missed_outgoing',
			'call_received'				 => 'call_received',
			'call_split'				 => 'call_split',
			'cancel_presentation'		 => 'cancel_presentation',
			'chat'						 => 'chat',
			'chat_bubble'				 => 'chat_bubble',
			'chat_bubble_outline'		 => 'chat_bubble_outline',
			'clear_all'					 => 'clear_all',
			'comment'					 => 'comment',
			'contact_mail'				 => 'contact_mail',
			'contact_phone'				 => 'contact_phone',
			'contacts'					 => 'contacts',
			'desktop_access_disabled'	 => 'desktop_access_disabled',
			'dialer_sip'				 => 'dialer_sip',
			'dialpad'					 => 'dialpad',
			'domain_disabled'			 => 'domain_disabled',
			'duo'						 => 'duo',
			'email'						 => 'email',
			'forum'						 => 'forum',
			'import_contacts'			 => 'import_contacts',
			'import_export'				 => 'import_export',
			'invert_colors_off'			 => 'invert_colors_off',
			'list_alt'					 => 'list_alt',
			'live_help'					 => 'live_help',
			'location_off'				 => 'location_off',
			'location_on'				 => 'location_on',
			'mail_outline'				 => 'mail_outline',
			'message'					 => 'message',
			'mobile_screen_share'		 => 'mobile_screen_share',
			'no_sim'					 => 'no_sim',
			'pause_presentation'		 => 'pause_presentation',
			'person_add_disabled'		 => 'person_add_disabled',
			'phone'						 => 'phone',
			'phone_disabled'			 => 'phone_disabled',
			'phone_enabled'				 => 'phone_enabled',
			'phonelink_erase'			 => 'phonelink_erase',
			'phonelink_lock'			 => 'phonelink_lock',
			'phonelink_ring'			 => 'phonelink_ring',
			'phonelink_setup'			 => 'phonelink_setup',
			'portable_wifi_off'			 => 'portable_wifi_off',
			'present_to_all'			 => 'present_to_all',
			'print_disabled'			 => 'print_disabled',
			'ring_volume'				 => 'ring_volume',
			'rss_feed'					 => 'rss_feed',
			'screen_share'				 => 'screen_share',
			'sentiment_satisfied_alt'	 => 'sentiment_satisfied_alt',
			'speaker_phone'				 => 'speaker_phone',
			'stay_current_landscape'	 => 'stay_current_landscape',
			'stay_current_portrait'		 => 'stay_current_portrait',
			'stay_primary_landscape'	 => 'stay_primary_landscape',
			'stay_primary_portrait'		 => 'stay_primary_portrait',
			'stop_screen_share'			 => 'stop_screen_share',
			'swap_calls'				 => 'swap_calls',
			'textsms'					 => 'textsms',
			'unsubscribe'				 => 'unsubscribe',
			'voicemail'					 => 'voicemail',
			'vpn_key'					 => 'vpn_key',
		];
		$content = [
			'add'					 => 'add',
			'add_box'				 => 'add_box',
			'add_circle'			 => 'add_circle',
			'add_circle_outline'	 => 'add_circle_outline',
			'amp_stories'			 => 'amp_stories',
			'archive'				 => 'archive',
			'backspace'				 => 'backspace',
			'ballot'				 => 'ballot',
			'block'					 => 'block',
			'clear'					 => 'clear',
			'create'				 => 'create',
			'delete_sweep'			 => 'delete_sweep',
			'drafts'				 => 'drafts',
			'dynamic_feed'			 => 'dynamic_feed',
			'file_copy'				 => 'file_copy',
			'filter_list'			 => 'filter_list',
			'flag'					 => 'flag',
			'font_download'			 => 'font_download',
			'forward'				 => 'forward',
			'gesture'				 => 'gesture',
			'how_to_reg'			 => 'how_to_reg',
			'how_to_vote'			 => 'how_to_vote',
			'inbox'					 => 'inbox',
			'link'					 => 'link',
			'link_off'				 => 'link_off',
			'low_priority'			 => 'low_priority',
			'mail'					 => 'mail',
			'markunread'			 => 'markunread',
			'move_to_inbox'			 => 'move_to_inbox',
			'next_week'				 => 'next_week',
			'outlined_flag'			 => 'outlined_flag',
			'policy'				 => 'policy',
			'redo'					 => 'redo',
			'remove'				 => 'remove',
			'remove_circle'			 => 'remove_circle',
			'remove_circle_outline'	 => 'remove_circle_outline',
			'reply'					 => 'reply',
			'reply_all'				 => 'reply_all',
			'report'				 => 'report',
			'report_off'			 => 'report_off',
			'save'					 => 'save',
			'save_alt'				 => 'save_alt',
			'select_all'			 => 'select_all',
			'send'					 => 'send',
			'sort'					 => 'sort',
			'square_foot'			 => 'square_foot',
			'text_format'			 => 'text_format',
			'unarchive'				 => 'unarchive',
			'undo'					 => 'undo',
			'waves'					 => 'waves',
			'weekend'				 => 'weekend',
			'where_to_vote'			 => 'where_to_vote',
		];
		$device = [
			'access_alarm'									 => 'access_alarm',
			'access_alarms'									 => 'access_alarms',
			'access_time'									 => 'access_time',
			'add_alarm'										 => 'add_alarm',
			'add_to_home_screen'							 => 'add_to_home_screen',
			'airplanemode_active'							 => 'airplanemode_active',
			'airplanemode_inactive'							 => 'airplanemode_inactive',
			'battery_alert'									 => 'battery_alert',
			'battery_charging_full'							 => 'battery_charging_full',
			'battery_full'									 => 'battery_full',
			'battery_std'									 => 'battery_std',
			'battery_unknown'								 => 'battery_unknown',
			'bluetooth'										 => 'bluetooth',
			'bluetooth_connected'							 => 'bluetooth_connected',
			'bluetooth_disabled'							 => 'bluetooth_disabled',
			'bluetooth_searching'							 => 'bluetooth_searching',
			'brightness_auto'								 => 'brightness_auto',
			'brightness_high'								 => 'brightness_high',
			'brightness_low'								 => 'brightness_low',
			'brightness_medium'								 => 'brightness_medium',
			'data_usage'									 => 'data_usage',
			'developer_mode'								 => 'developer_mode',
			'devices'										 => 'devices',
			'dvr'											 => 'dvr',
			'gps_fixed'										 => 'gps_fixed',
			'gps_not_fixed'									 => 'gps_not_fixed',
			'gps_off'										 => 'gps_off',
			'graphic_eq'									 => 'graphic_eq',
			'location_disabled'								 => 'location_disabled',
			'location_searching'							 => 'location_searching',
			'mobile_friendly'								 => 'mobile_friendly',
			'mobile_off'									 => 'mobile_off',
			'nfc'											 => 'nfc',
			'screen_lock_landscape'							 => 'screen_lock_landscape',
			'screen_lock_portrait'							 => 'screen_lock_portrait',
			'screen_lock_rotation'							 => 'screen_lock_rotation',
			'screen_rotation'								 => 'screen_rotation',
			'sd_storage'									 => 'sd_storage',
			'settings_system_daydream'						 => 'settings_system_daydream',
			'signal_cellular_4_bar'							 => 'signal_cellular_4_bar',
			'signal_cellular_alt'							 => 'signal_cellular_alt',
			'signal_cellular_connected_no_internet_4_bar'	 => 'signal_cellular_connected_no_internet_4_bar',
			'signal_cellular_no_sim'						 => 'signal_cellular_no_sim',
			'signal_cellular_null'							 => 'signal_cellular_null',
			'signal_cellular_off'							 => 'signal_cellular_off',
			'signal_wifi_4_bar'								 => 'signal_wifi_4_bar',
			'signal_wifi_4_bar_lock'						 => 'signal_wifi_4_bar_lock',
			'signal_wifi_off'								 => 'signal_wifi_off',
			'storage'										 => 'storage',
			'usb'											 => 'usb',
			'wallpaper'										 => 'wallpaper',
			'widgets'										 => 'widgets',
			'wifi_lock'										 => 'wifi_lock',
			'wifi_tethering'								 => 'wifi_tethering',
		];
		$editor = [
			'add_comment'					 => 'add_comment',
			'attach_file'					 => 'attach_file',
			'attach_money'					 => 'attach_money',
			'bar_chart'						 => 'bar_chart',
			'border_all'					 => 'border_all',
			'border_bottom'					 => 'border_bottom',
			'border_clear'					 => 'border_clear',
			'border_horizontal'				 => 'border_horizontal',
			'border_inner'					 => 'border_inner',
			'border_left'					 => 'border_left',
			'border_outer'					 => 'border_outer',
			'border_right'					 => 'border_right',
			'border_style'					 => 'border_style',
			'border_top'					 => 'border_top',
			'border_vertical'				 => 'border_vertical',
			'bubble_chart'					 => 'bubble_chart',
			'drag_handle'					 => 'drag_handle',
			'format_align_center'			 => 'format_align_center',
			'format_align_justify'			 => 'format_align_justify',
			'format_align_left'				 => 'format_align_left',
			'format_align_right'			 => 'format_align_right',
			'format_bold'					 => 'format_bold',
			'format_clear'					 => 'format_clear',
			'format_color_reset'			 => 'format_color_reset',
			'format_indent_decrease'		 => 'format_indent_decrease',
			'format_indent_increase'		 => 'format_indent_increase',
			'format_italic'					 => 'format_italic',
			'format_line_spacing'			 => 'format_line_spacing',
			'format_list_bulleted'			 => 'format_list_bulleted',
			'format_list_numbered'			 => 'format_list_numbered',
			'format_list_numbered_rtl'		 => 'format_list_numbered_rtl',
			'format_paint'					 => 'format_paint',
			'format_quote'					 => 'format_quote',
			'format_shapes'					 => 'format_shapes',
			'format_size'					 => 'format_size',
			'format_strikethrough'			 => 'format_strikethrough',
			'format_textdirection_l_to_r'	 => 'format_textdirection_l_to_r',
			'format_textdirection_r_to_l'	 => 'format_textdirection_r_to_l',
			'format_underlined'				 => 'format_underlined',
			'functions'						 => 'functions',
			'height'						 => 'height',
			'highlight'						 => 'highlight',
			'insert_chart'					 => 'insert_chart',
			'insert_chart_outlined'			 => 'insert_chart_outlined',
			'insert_comment'				 => 'insert_comment',
			'insert_drive_file'				 => 'insert_drive_file',
			'insert_emoticon'				 => 'insert_emoticon',
			'insert_invitation'				 => 'insert_invitation',
			'insert_link'					 => 'insert_link',
			'insert_photo'					 => 'insert_photo',
			'linear_scale'					 => 'linear_scale',
			'merge_type'					 => 'merge_type',
			'mode_comment'					 => 'mode_comment',
			'monetization_on'				 => 'monetization_on',
			'money_off'						 => 'money_off',
			'multiline_chart'				 => 'multiline_chart',
			'notes'							 => 'notes',
			'pie_chart'						 => 'pie_chart',
			'post_add'						 => 'post_add',
			'publish'						 => 'publish',
			'scatter_plot'					 => 'scatter_plot',
			'score'							 => 'score',
			'short_text'					 => 'short_text',
			'show_chart'					 => 'show_chart',
			'space_bar'						 => 'space_bar',
			'strikethrough_s'				 => 'strikethrough_s',
			'table_chart'					 => 'table_chart',
			'text_fields'					 => 'text_fields',
			'title'							 => 'title',
			'vertical_align_bottom'			 => 'vertical_align_bottom',
			'vertical_align_center'			 => 'vertical_align_center',
			'vertical_align_top'			 => 'vertical_align_top',
			'wrap_text'						 => 'wrap_text',
		];
		$file = [
			'attachment'		 => 'attachment',
			'cloud'				 => 'cloud',
			'cloud_circle'		 => 'cloud_circle',
			'cloud_done'		 => 'cloud_done',
			'cloud_download'	 => 'cloud_download',
			'cloud_off'			 => 'cloud_off',
			'cloud_queue'		 => 'cloud_queue',
			'cloud_upload'		 => 'cloud_upload',
			'create_new_folder'	 => 'create_new_folder',
			'folder'			 => 'folder',
			'folder_open'		 => 'folder_open',
			'folder_shared'		 => 'folder_shared',
		];
		$hardware = [
			'cast'					 => 'cast',
			'cast_connected'		 => 'cast_connected',
			'computer'				 => 'computer',
			'desktop_mac'			 => 'desktop_mac',
			'desktop_windows'		 => 'desktop_windows',
			'developer_board'		 => 'developer_board',
			'device_hub'			 => 'device_hub',
			'device_unknown'		 => 'device_unknown',
			'devices_other'			 => 'devices_other',
			'dock'					 => 'dock',
			'gamepad'				 => 'gamepad',
			'headset'				 => 'headset',
			'headset_mic'			 => 'headset_mic',
			'keyboard'				 => 'keyboard',
			'keyboard_arrow_down'	 => 'keyboard_arrow_down',
			'keyboard_arrow_left'	 => 'keyboard_arrow_left',
			'keyboard_arrow_right'	 => 'keyboard_arrow_right',
			'keyboard_arrow_up'		 => 'keyboard_arrow_up',
			'keyboard_backspace'	 => 'keyboard_backspace',
			'keyboard_capslock'		 => 'keyboard_capslock',
			'keyboard_hide'			 => 'keyboard_hide',
			'keyboard_return'		 => 'keyboard_return',
			'keyboard_tab'			 => 'keyboard_tab',
			'keyboard_voice'		 => 'keyboard_voice',
			'laptop'				 => 'laptop',
			'laptop_chromebook'		 => 'laptop_chromebook',
			'laptop_mac'			 => 'laptop_mac',
			'laptop_windows'		 => 'laptop_windows',
			'memory'				 => 'memory',
			'mouse'					 => 'mouse',
			'phone_android'			 => 'phone_android',
			'phone_iphone'			 => 'phone_iphone',
			'phonelink'				 => 'phonelink',
			'phonelink_off'			 => 'phonelink_off',
			'power_input'			 => 'power_input',
			'router'				 => 'router',
			'scanner'				 => 'scanner',
			'security'				 => 'security',
			'sim_card'				 => 'sim_card',
			'smartphone'			 => 'smartphone',
			'speaker'				 => 'speaker',
			'speaker_group'			 => 'speaker_group',
			'tablet'				 => 'tablet',
			'tablet_android'		 => 'tablet_android',
			'tablet_mac'			 => 'tablet_mac',
			'toys'					 => 'toys',
			'tv'					 => 'tv',
			'videogame_asset'		 => 'videogame_asset',
			'watch'					 => 'watch',
		];
		$image = [
			'camera_roll'				 => 'camera_roll',
			'add_a_photo'				 => 'add_a_photo',
			'add_photo_alternate'		 => 'add_photo_alternate',
			'add_to_photos'				 => 'add_to_photos',
			'adjust'					 => 'adjust',
			'assistant'					 => 'assistant',
			'assistant_photo'			 => 'assistant_photo',
			'audiotrack'				 => 'audiotrack',
			'blur_circular'				 => 'blur_circular',
			'blur_linear'				 => 'blur_linear',
			'blur_off'					 => 'blur_off',
			'blur_on'					 => 'blur_on',
			'brightness_1'				 => 'brightness_1',
			'brightness_2'				 => 'brightness_2',
			'brightness_3'				 => 'brightness_3',
			'brightness_4'				 => 'brightness_4',
			'brightness_5'				 => 'brightness_5',
			'brightness_6'				 => 'brightness_6',
			'brightness_7'				 => 'brightness_7',
			'broken_image'				 => 'broken_image',
			'brush'						 => 'brush',
			'burst_mode'				 => 'burst_mode',
			'camera'					 => 'camera',
			'camera_alt'				 => 'camera_alt',
			'camera_front'				 => 'camera_front',
			'camera_rear'				 => 'camera_rear',
			'center_focus_strong'		 => 'center_focus_strong',
			'center_focus_weak'			 => 'center_focus_weak',
			'collections'				 => 'collections',
			'collections_bookmark'		 => 'collections_bookmark',
			'color_lens'				 => 'color_lens',
			'colorize'					 => 'colorize',
			'compare'					 => 'compare',
			'control_point'				 => 'control_point',
			'control_point_duplicate'	 => 'control_point_duplicate',
			'crop'						 => 'crop',
			'crop_16_9'					 => 'crop_16_9',
			'crop_3_2'					 => 'crop_3_2',
			'crop_5_4'					 => 'crop_5_4',
			'crop_7_5'					 => 'crop_7_5',
			'crop_din'					 => 'crop_din',
			'crop_free'					 => 'crop_free',
			'crop_landscape'			 => 'crop_landscape',
			'crop_original'				 => 'crop_original',
			'crop_portrait'				 => 'crop_portrait',
			'crop_rotate'				 => 'crop_rotate',
			'crop_square'				 => 'crop_square',
			'dehaze'					 => 'dehaze',
			'details'					 => 'details',
			'edit'						 => 'edit',
			'euro'						 => 'euro',
			'exposure'					 => 'exposure',
			'exposure_neg_1'			 => 'exposure_neg_1',
			'exposure_neg_2'			 => 'exposure_neg_2',
			'exposure_plus_1'			 => 'exposure_plus_1',
			'exposure_plus_2'			 => 'exposure_plus_2',
			'exposure_zero'				 => 'exposure_zero',
			'filter'					 => 'filter',
			'filter_1'					 => 'filter_1',
			'filter_2'					 => 'filter_2',
			'filter_3'					 => 'filter_3',
			'filter_4'					 => 'filter_4',
			'filter_5'					 => 'filter_5',
			'filter_6'					 => 'filter_6',
			'filter_7'					 => 'filter_7',
			'filter_8'					 => 'filter_8',
			'filter_9'					 => 'filter_9',
			'filter_9_plus'				 => 'filter_9_plus',
			'filter_b_and_w'			 => 'filter_b_and_w',
			'filter_center_focus'		 => 'filter_center_focus',
			'filter_drama'				 => 'filter_drama',
			'filter_frames'				 => 'filter_frames',
			'filter_hdr'				 => 'filter_hdr',
			'filter_none'				 => 'filter_none',
			'filter_tilt_shift'			 => 'filter_tilt_shift',
			'filter_vintage'			 => 'filter_vintage',
			'flare'						 => 'flare',
			'flash_auto'				 => 'flash_auto',
			'flash_off'					 => 'flash_off',
			'flash_on'					 => 'flash_on',
			'flip'						 => 'flip',
			'flip_camera_android'		 => 'flip_camera_android',
			'flip_camera_ios'			 => 'flip_camera_ios',
			'gradient'					 => 'gradient',
			'grain'						 => 'grain',
			'grid_off'					 => 'grid_off',
			'grid_on'					 => 'grid_on',
			'hdr_off'					 => 'hdr_off',
			'hdr_on'					 => 'hdr_on',
			'hdr_strong'				 => 'hdr_strong',
			'hdr_weak'					 => 'hdr_weak',
			'healing'					 => 'healing',
			'image'						 => 'image',
			'image_aspect_ratio'		 => 'image_aspect_ratio',
			'image_search'				 => 'image_search',
			'iso'						 => 'iso',
			'landscape'					 => 'landscape',
			'leak_add'					 => 'leak_add',
			'leak_remove'				 => 'leak_remove',
			'lens'						 => 'lens',
			'linked_camera'				 => 'linked_camera',
			'looks'						 => 'looks',
			'looks_3'					 => 'looks_3',
			'looks_4'					 => 'looks_4',
			'looks_5'					 => 'looks_5',
			'looks_6'					 => 'looks_6',
			'looks_one'					 => 'looks_one',
			'looks_two'					 => 'looks_two',
			'loupe'						 => 'loupe',
			'monochrome_photos'			 => 'monochrome_photos',
			'movie_creation'			 => 'movie_creation',
			'movie_filter'				 => 'movie_filter',
			'music_note'				 => 'music_note',
			'music_off'					 => 'music_off',
			'nature'					 => 'nature',
			'nature_people'				 => 'nature_people',
			'navigate_before'			 => 'navigate_before',
			'navigate_next'				 => 'navigate_next',
			'palette'					 => 'palette',
			'panorama'					 => 'panorama',
			'panorama_fish_eye'			 => 'panorama_fish_eye',
			'panorama_horizontal'		 => 'panorama_horizontal',
			'panorama_vertical'			 => 'panorama_vertical',
			'panorama_wide_angle'		 => 'panorama_wide_angle',
			'photo'						 => 'photo',
			'photo_album'				 => 'photo_album',
			'photo_camera'				 => 'photo_camera',
			'photo_filter'				 => 'photo_filter',
			'photo_library'				 => 'photo_library',
			'photo_size_select_actual'	 => 'photo_size_select_actual',
			'photo_size_select_large'	 => 'photo_size_select_large',
			'photo_size_select_small'	 => 'photo_size_select_small',
			'picture_as_pdf'			 => 'picture_as_pdf',
			'portrait'					 => 'portrait',
			'remove_red_eye'			 => 'remove_red_eye',
			'rotate_90_degrees_ccw'		 => 'rotate_90_degrees_ccw',
			'rotate_left'				 => 'rotate_left',
			'rotate_right'				 => 'rotate_right',
			'shutter_speed'				 => 'shutter_speed',
			'slideshow'					 => 'slideshow',
			'straighten'				 => 'straighten',
			'style'						 => 'style',
			'switch_camera'				 => 'switch_camera',
			'switch_video'				 => 'switch_video',
			'tag_faces'					 => 'tag_faces',
			'texture'					 => 'texture',
			'timelapse'					 => 'timelapse',
			'timer'						 => 'timer',
			'timer_10'					 => 'timer_10',
			'timer_3'					 => 'timer_3',
			'timer_off'					 => 'timer_off',
			'tonality'					 => 'tonality',
			'transform'					 => 'transform',
			'tune'						 => 'tune',
			'view_comfy'				 => 'view_comfy',
			'view_compact'				 => 'view_compact',
			'vignette'					 => 'vignette',
			'wb_auto'					 => 'wb_auto',
			'wb_cloudy'					 => 'wb_cloudy',
			'wb_incandescent'			 => 'wb_incandescent',
			'wb_iridescent'				 => 'wb_iridescent',
			'wb_sunny'					 => 'wb_sunny',
		];
		$maps = [
			'category'					 => 'category',
			'360'						 => '360',
			'add_location'				 => 'add_location',
			'atm'						 => 'atm',
			'beenhere'					 => 'beenhere',
			'compass_calibration'		 => 'compass_calibration',
			'departure_board'			 => 'departure_board',
			'directions'				 => 'directions',
			'directions_bike'			 => 'directions_bike',
			'directions_boat'			 => 'directions_boat',
			'directions_bus'			 => 'directions_bus',
			'directions_car'			 => 'directions_car',
			'directions_railway'		 => 'directions_railway',
			'directions_run'			 => 'directions_run',
			'directions_subway'			 => 'directions_subway',
			'directions_transit'		 => 'directions_transit',
			'directions_walk'			 => 'directions_walk',
			'edit_attributes'			 => 'edit_attributes',
			'edit_location'				 => 'edit_location',
			'ev_station'				 => 'ev_station',
			'fastfood'					 => 'fastfood',
			'flight'					 => 'flight',
			'hotel'						 => 'hotel',
			'layers'					 => 'layers',
			'layers_clear'				 => 'layers_clear',
			'local_activity'			 => 'local_activity',
			'local_airport'				 => 'local_airport',
			'local_atm'					 => 'local_atm',
			'local_bar'					 => 'local_bar',
			'local_cafe'				 => 'local_cafe',
			'local_car_wash'			 => 'local_car_wash',
			'local_convenience_store'	 => 'local_convenience_store',
			'local_dining'				 => 'local_dining',
			'local_drink'				 => 'local_drink',
			'local_florist'				 => 'local_florist',
			'local_gas_station'			 => 'local_gas_station',
			'local_grocery_store'		 => 'local_grocery_store',
			'local_hospital'			 => 'local_hospital',
			'local_hotel'				 => 'local_hotel',
			'local_laundry_service'		 => 'local_laundry_service',
			'local_library'				 => 'local_library',
			'local_mall'				 => 'local_mall',
			'local_movies'				 => 'local_movies',
			'local_offer'				 => 'local_offer',
			'local_parking'				 => 'local_parking',
			'local_pharmacy'			 => 'local_pharmacy',
			'local_phone'				 => 'local_phone',
			'local_pizza'				 => 'local_pizza',
			'local_play'				 => 'local_play',
			'local_post_office'			 => 'local_post_office',
			'local_printshop'			 => 'local_printshop',
			'local_see'					 => 'local_see',
			'local_shipping'			 => 'local_shipping',
			'local_taxi'				 => 'local_taxi',
			'map'						 => 'map',
			'menu_book'					 => 'menu_book',
			'money'						 => 'money',
			'museum'					 => 'museum',
			'my_location'				 => 'my_location',
			'navigation'				 => 'navigation',
			'near_me'					 => 'near_me',
			'not_listed_location'		 => 'not_listed_location',
			'person_pin'				 => 'person_pin',
			'person_pin_circle'			 => 'person_pin_circle',
			'pin_drop'					 => 'pin_drop',
			'place'						 => 'place',
			'rate_review'				 => 'rate_review',
			'restaurant'				 => 'restaurant',
			'restaurant_menu'			 => 'restaurant_menu',
			'satellite'					 => 'satellite',
			'store_mall_directory'		 => 'store_mall_directory',
			'streetview'				 => 'streetview',
			'subway'					 => 'subway',
			'terrain'					 => 'terrain',
			'traffic'					 => 'traffic',
			'train'						 => 'train',
			'tram'						 => 'tram',
			'transfer_within_a_station'	 => 'transfer_within_a_station',
			'transit_enterexit'			 => 'transit_enterexit',
			'trip_origin'				 => 'trip_origin',
			'two_wheeler'				 => 'two_wheeler',
			'zoom_out_map'				 => 'zoom_out_map',
		];
		$navigation = [
			'apps'						 => 'apps',
			'arrow_back'				 => 'arrow_back',
			'arrow_back_ios'			 => 'arrow_back_ios',
			'arrow_downward'			 => 'arrow_downward',
			'arrow_drop_down'			 => 'arrow_drop_down',
			'arrow_drop_down_circle'	 => 'arrow_drop_down_circle',
			'arrow_drop_up'				 => 'arrow_drop_up',
			'arrow_forward'				 => 'arrow_forward',
			'arrow_forward_ios'			 => 'arrow_forward_ios',
			'arrow_left'				 => 'arrow_left',
			'arrow_right'				 => 'arrow_right',
			'arrow_upward'				 => 'arrow_upward',
			'cancel'					 => 'cancel',
			'check'						 => 'check',
			'chevron_left'				 => 'chevron_left',
			'chevron_right'				 => 'chevron_right',
			'close'						 => 'close',
			'double_arrow'				 => 'double_arrow',
			'expand_less'				 => 'expand_less',
			'expand_more'				 => 'expand_more',
			'first_page'				 => 'first_page',
			'fullscreen'				 => 'fullscreen',
			'fullscreen_exit'			 => 'fullscreen_exit',
			'home_work'					 => 'home_work',
			'last_page'					 => 'last_page',
			'menu'						 => 'menu',
			'menu_open'					 => 'menu_open',
			'more_horiz'				 => 'more_horiz',
			'more_vert'					 => 'more_vert',
			'refresh'					 => 'refresh',
			'subdirectory_arrow_left'	 => 'subdirectory_arrow_left',
			'subdirectory_arrow_right'	 => 'subdirectory_arrow_right',
			'unfold_less'				 => 'unfold_less',
			'unfold_more'				 => 'unfold_more',
		];
		$notification = [
			'account_tree'					 => 'account_tree',
			'adb'							 => 'adb',
			'airline_seat_flat'				 => 'airline_seat_flat',
			'airline_seat_flat_angled'		 => 'airline_seat_flat_angled',
			'airline_seat_individual_suite'	 => 'airline_seat_individual_suite',
			'airline_seat_legroom_extra'	 => 'airline_seat_legroom_extra',
			'airline_seat_legroom_normal'	 => 'airline_seat_legroom_normal',
			'airline_seat_legroom_reduced'	 => 'airline_seat_legroom_reduced',
			'airline_seat_recline_extra'	 => 'airline_seat_recline_extra',
			'airline_seat_recline_normal'	 => 'airline_seat_recline_normal',
			'bluetooth_audio'				 => 'bluetooth_audio',
			'confirmation_number'			 => 'confirmation_number',
			'disc_full'						 => 'disc_full',
			'drive_eta'						 => 'drive_eta',
			'enhanced_encryption'			 => 'enhanced_encryption',
			'event_available'				 => 'event_available',
			'event_busy'					 => 'event_busy',
			'event_note'					 => 'event_note',
			'folder_special'				 => 'folder_special',
			'live_tv'						 => 'live_tv',
			'mms'							 => 'mms',
			'more'							 => 'more',
			'network_check'					 => 'network_check',
			'network_locked'				 => 'network_locked',
			'no_encryption'					 => 'no_encryption',
			'ondemand_video'				 => 'ondemand_video',
			'personal_video'				 => 'personal_video',
			'phone_bluetooth_speaker'		 => 'phone_bluetooth_speaker',
			'phone_callback'				 => 'phone_callback',
			'phone_forwarded'				 => 'phone_forwarded',
			'phone_in_talk'					 => 'phone_in_talk',
			'phone_locked'					 => 'phone_locked',
			'phone_missed'					 => 'phone_missed',
			'phone_paused'					 => 'phone_paused',
			'power'							 => 'power',
			'power_off'						 => 'power_off',
			'priority_high'					 => 'priority_high',
			'sd_card'						 => 'sd_card',
			'sms'							 => 'sms',
			'sms_failed'					 => 'sms_failed',
			'sync'							 => 'sync',
			'sync_disabled'					 => 'sync_disabled',
			'sync_problem'					 => 'sync_problem',
			'system_update'					 => 'system_update',
			'tap_and_play'					 => 'tap_and_play',
			'time_to_leave'					 => 'time_to_leave',
			'tv_off'						 => 'tv_off',
			'vibration'						 => 'vibration',
			'voice_chat'					 => 'voice_chat',
			'vpn_lock'						 => 'vpn_lock',
			'wc'							 => 'wc',
			'wifi'							 => 'wifi',
			'wifi_off'						 => 'wifi_off',
		];
		$places = [
			'ac_unit'			 => 'ac_unit',
			'airport_shuttle'	 => 'airport_shuttle',
			'all_inclusive'		 => 'all_inclusive',
			'apartment'			 => 'apartment',
			'bathtub'			 => 'bathtub',
			'beach_access'		 => 'beach_access',
			'business_center'	 => 'business_center',
			'casino'			 => 'casino',
			'child_care'		 => 'child_care',
			'child_friendly'	 => 'child_friendly',
			'fitness_center'	 => 'fitness_center',
			'free_breakfast'	 => 'free_breakfast',
			'golf_course'		 => 'golf_course',
			'hot_tub'			 => 'hot_tub',
			'house'				 => 'house',
			'kitchen'			 => 'kitchen',
			'meeting_room'		 => 'meeting_room',
			'no_meeting_room'	 => 'no_meeting_room',
			'pool'				 => 'pool',
			'room_service'		 => 'room_service',
			'rv_hookup'			 => 'rv_hookup',
			'smoke_free'		 => 'smoke_free',
			'smoking_rooms'		 => 'smoking_rooms',
			'spa'				 => 'spa',
			'storefront'		 => 'storefront',
		];
		$social = [
			'people_outline'				 => 'people_outline',
			'cake'							 => 'cake',
			'deck'							 => 'deck',
			'domain'						 => 'domain',
			'emoji_emotions'				 => 'emoji_emotions',
			'emoji_events'					 => 'emoji_events',
			'emoji_flags'					 => 'emoji_flags',
			'emoji_food_beverage'			 => 'emoji_food_beverage',
			'emoji_nature'					 => 'emoji_nature',
			'emoji_objects'					 => 'emoji_objects',
			'emoji_people'					 => 'emoji_people',
			'emoji_symbols'					 => 'emoji_symbols',
			'emoji_transportation'			 => 'emoji_transportation',
			'fireplace'						 => 'fireplace',
			'group'							 => 'group',
			'group_add'						 => 'group_add',
			'king_bed'						 => 'king_bed',
			'location_city'					 => 'location_city',
			'mood'							 => 'mood',
			'mood_bad'						 => 'mood_bad',
			'nights_stay'					 => 'nights_stay',
			'notifications'					 => 'notifications',
			'notifications_active'			 => 'notifications_active',
			'notifications_none'			 => 'notifications_none',
			'notifications_off'				 => 'notifications_off',
			'notifications_paused'			 => 'notifications_paused',
			'outdoor_grill'					 => 'outdoor_grill',
			'pages'							 => 'pages',
			'party_mode'					 => 'party_mode',
			'people'						 => 'people',
			'people_alt'					 => 'people_alt',
			'person'						 => 'person',
			'person_add'					 => 'person_add',
			'person_outline'				 => 'person_outline',
			'plus_one'						 => 'plus_one',
			'poll'							 => 'poll',
			'public'						 => 'public',
			'school'						 => 'school',
			'sentiment_dissatisfied'		 => 'sentiment_dissatisfied',
			'sentiment_satisfied'			 => 'sentiment_satisfied',
			'sentiment_very_dissatisfied'	 => 'sentiment_very_dissatisfied',
			'sentiment_very_satisfied'		 => 'sentiment_very_satisfied',
			'share'							 => 'share',
			'single_bed'					 => 'single_bed',
			'sports'						 => 'sports',
			'sports_baseball'				 => 'sports_baseball',
			'sports_basketball'				 => 'sports_basketball',
			'sports_cricket'				 => 'sports_cricket',
			'sports_esports'				 => 'sports_esports',
			'sports_football'				 => 'sports_football',
			'sports_golf'					 => 'sports_golf',
			'sports_handball'				 => 'sports_handball',
			'sports_hockey'					 => 'sports_hockey',
			'sports_kabaddi'				 => 'sports_kabaddi',
			'sports_mma'					 => 'sports_mma',
			'sports_motorsports'			 => 'sports_motorsports',
			'sports_rugby'					 => 'sports_rugby',
			'sports_soccer'					 => 'sports_soccer',
			'sports_tennis'					 => 'sports_tennis',
			'sports_volleyball'				 => 'sports_volleyball',
			'thumb_down_alt'				 => 'thumb_down_alt',
			'thumb_up_alt'					 => 'thumb_up_alt',
			'whatshot'						 => 'whatshot',
		];
		$toggle = [
			'check_box'					 => 'check_box',
			'check_box_outline_blank'	 => 'check_box_outline_blank',
			'indeterminate_check_box'	 => 'indeterminate_check_box',
			'radio_button_checked'		 => 'radio_button_checked',
			'radio_button_unchecked'	 => 'radio_button_unchecked',
			'star'						 => 'star',
			'star_border'				 => 'star_border',
			'star_half'					 => 'star_half',
			'star_outline'				 => 'star_outline',
			'toggle_off'				 => 'toggle_off',
			'toggle_on'					 => 'toggle_on',
		];

		$return = [];
		 
		// tout par default
		if( count($byGroups) == 0 && count($byIcons) == 0 ){
			$byGroups = $allCat;
		}
		
		// On prend par unitairement
		foreach ($byIcons as $value) { 
			$return = array_merge($return, [$value => $value] ); 
		}
		 
		// On prend par groupements
		foreach ($byGroups as $value) {
			if( isset( $$value ) ){
				$return = array_merge($return, $$value);
			}
		}
		
		
		return $return;
    }

}
